### ISSUE TITLE
Add comment sections/reblogging

### ISSUE THREAD

**Issue by ValorZard** [NfNitLoop/feoblog#46]
This project reminds me a lot of tumblr, so it would be cool if you could bring back some of tumblrs features into this.

**Comment by NfNitLoop** [comment]
I agree!

Comments were [added in v0.2.0](https://github.com/NfNitLoop/feoblog/blob/v0.4.0/CHANGELOG.md#version-020).

(And a big part of the v0.4.0 work was making the Web 2.0 client the default view, because it actually renders comment replies.)

And I've already got #6 to add Reblogging, so I'm going to close this one as a duplicate. But if you think I didn't quite capture those features, please feel free to re-open this with more detail. 😃
